name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write
  packages: write

jobs:
  secret-scan:
    uses: ./.github/workflows/gitleaks.yml

  build-image:
    uses: ./.github/workflows/build-image.yml
    needs: secret-scan

  lint-format:
    uses: ./.github/workflows/lint-format.yml
    needs: build-image

  unit-sec-scan:
    uses: ./.github/workflows/unit-sec-test.yml
    needs: lint-format

  push-docker-image:
    uses: ./.github/workflows/push-docker-image.yml
    needs: unit-sec-scan

  security-feedback-report:
    if: always()
    permissions:
      contents: read
      actions: read
      checks: read
    needs:
      - secret-scan
      - build-image
      - lint-format
      - unit-sec-scan
    uses: ./.github/workflows/security-report.yml
    with:
      report_name: Main Branch Security Feedback Report
      artifact_name: main-security-feedback-report
